MVC_Core_HW/Controllers/RestaurantController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using MVC_Core_HW.Helpers;
using MVC_Core_HW.Helpers.repository;
using MVC_Core_HW.Models;
using MVC_Core_HW.Models.Entities;
using MVC_Core_HW.Models.ViewModels;

namespace MVC_Core_HW.Controllers
{
    
    public class RestaurantController : Controller
    {
        private IMealRepository _mealRepository;
        private IIngredientRepository _ingredientRepository;

        public RestaurantController(IMealRepository mealRepository, IIngredientRepository ingredientRepository)
        {
            this._mealRepository = mealRepository;
            this._ingredientRepository = ingredientRepository;
        }


        public IActionResult Index()
        {
            List<ListMealsViewModel> meals = this._mealRepository.ListAllMeals();
            return View(meals);
        }

        [HttpGet]
        public IActionResult Delete(int? id)
        {
            if (id == null) return NotFound($"Select meal to delete first");

            var meal = this._mealRepository.GetMealById(id.Value);

            if (meal == null) return NotFound($"Meal with id : {id} doesn't exist!");

            return View(meal);
        }

        [HttpPost]
        public IActionResult Delete(Meal meal)
        {
            if (meal == null) return NotFound($"Cannot be deleted, doesn't exist!");
            if (this._mealRepository.DeleteMeal(meal)) return RedirectToAction("Index");

            return NotFound($"Cannot be deleted, doesn't exist!");
        }

        [Route("Restaurant/create/meal")]
        [HttpGet]
        public IActionResult CreateMeal()
        {
            return View(this.CreateTheViewModelForMeal());
        }

        private CreateMealViewModel CreateTheViewModelForMeal()
        {
            var allTypes = this._mealRepository.GetAllMealTypes();
            var allIngredients = this._ingredientRepository.ListAllIngredients().Select(i => new SelectListItem { Value = i.Id.ToString(), Text = i.Name }).ToList();
            CreateMealViewModel createMealViewModel = new CreateMealViewModel(allIngredients, allTypes);
            return createMealViewModel;
        }

        [Route("Restaurant/create/meal")]
        [HttpPost]
        public IActionResult CreateMeal(CreateMealViewModel createMealViewModel)
        {
            if (!ModelState.IsValid) return RedirectToAction("CreateMeal");
            if (createMealViewModel.Type == "Desert" && createMealViewModel.Price < 250)
            {
                return View(this.CreateTheViewModelForMeal());
            }
            Meal meal = new Meal();
            meal.Name = createMealViewModel.Name;
            meal.Price = createMealViewModel.Price;
            meal.Type = createMealViewModel.Type;
            meal.Ingredients = createMealViewModel.Ingredients.Select(x => Convert.ToInt32(x)).ToList();
            meal.IsVeggie = createMealViewModel.IsVeggie != null ? createMealViewModel.IsVeggie : false;

            this._mealRepository.CreateMeal(meal);
            return RedirectToAction("Index");
        }

        [Route("Restaurant/{type}/meals")]
        public IActionResult MealsByType(string type)
        {
            List<Meal> meals = this._mealRepository.GetMealsByType(type.ToLower());
            Helper helper = new Helper();
            string time = DateTime.Now.ToString("HH:mm:ss tt");
            helper.Log(new SearchTypeLog(type.ToLower(), time));
            return View(meals);
        }
    }
}

MVC_Core_HW/Controllers/SuppliesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MVC_Core_HW.Helpers.repository;
using MVC_Core_HW.Models.Entities;
using MVC_Core_HW.Models.ViewModels;

namespace MVC_Core_HW.Controllers
{
    public class SuppliesController : Controller
    {

        private IIngredientRepository _ingredientRepository;

        public SuppliesController(IIngredientRepository ingredientRepo)
        {
            this._ingredientRepository = ingredientRepo;
        }

        public IActionResult Index()
        {
            SuppliesViewModel suppliesViewModel = new SuppliesViewModel();
            suppliesViewModel.Ingredients = this._ingredientRepository.ListAllIngredients();
            suppliesViewModel.IngredientViewModel = new IngredientCreateViewModel();
            return View(suppliesViewModel);
        }

        [HttpPost]
        public IActionResult Create()
        {
            IngredientCreateViewModel ingredientCreateViewModel = new IngredientCreateViewModel();
            try
            {
                ingredientCreateViewModel.Name = Request.Form["Name"].ToString();
                ingredientCreateViewModel.ExpirationDate = Request.Form["ExpirationDate"].ToString();
                if (ingredientCreateViewModel.Name == "" || ingredientCreateViewModel.ExpirationDate == "") throw new FormatException();
                ingredientCreateViewModel.Quantity = Convert.ToInt16(Request.Form["Quantity"].ToString());
            }catch(FormatException e)
            {
                return NotFound(e.Message);
            }
            this._ingredientRepository.CreateIngredient(ingredientCreateViewModel);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Delete(int? id)
        {
            if (id == null) return NotFound($"Ingredient with id : {id} doesn't exist!");

            var supply = this._ingredientRepository.GetIngredientById(id.Value);

            if(supply == null) return NotFound($"Ingredient with id : {id} doesn't exist!");

            return View(supply);
        }

        [HttpGet]
        public IActionResult Edit(int? id)
        {
            if (id == null) return NotFound($"Ingredient with id : {id} doesn't exist!");

            var supply = this._ingredientRepository.GetIngredientById(id.Value);

            if (supply == null) return NotFound($"Ingredient with id : {id} doesn't exist!");

            return View(supply);
        }

        [HttpPost]
        public IActionResult Edit(Ingredient ingredient)
        {
            if (ingredient == null) return NotFound($"Cannot be updated, doesn't exist!");
            this._ingredientRepository.UpdateIngredient(ingredient);

            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Delete(Ingredient ingredient)
        {
            if (ingredient == null) return NotFound($"Cannot be deleted, doesn't exist!");
            if(this._ingredientRepository.DeleteIngredient(ingredient)) return RedirectToAction("Index");

            return NotFound($"Cannot be deleted, doesn't exist!");
        }


        [HttpGet]
        [Route("Supplies/Expired")]
        public IActionResult ExpiredProducts()
        {
            var ingredients = this._ingredientRepository.ExpiredProducts();
            return View("ListIngredients", ingredients);
        }

        [HttpGet]
        [Route("Supplies/Need")]
        public IActionResult NeededProducts()
        {
            var ingredients = this._ingredientRepository.NeededProducts();
            return View("ListIngredients", ingredients);
        }
    }
}

MVC_Core_HW/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVC_Core_HW</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.min.css" />

    
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MVC_Core_HW</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Supplies" asp-action="Index">Supplies</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Restaurant" asp-action="Index">Menu</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - MVC_Core_HW - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    <script src="https://cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.15/js/dataTables.bootstrap4.min.js "></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.1/jquery.validate.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.11/jquery.validate.unobtrusive.min.js"></script>
    

    @RenderSection("Scripts", required: false)
</body>
</html>